apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-papa-deploy
  namespace: civil-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-papa
  template:
    metadata:
      labels:
        app: web-papa
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: web-papa-container
          image: ghcr.io/matucr/web-papa:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          # Liveness probe para que K8s sepa si el Nginx se colgó
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
