apiVersion: v1
kind: Service
metadata:
  name: web-papa-service    # Nombre que usará el Ingress
  namespace: civil-web
spec:
  selector:
    app: web-papa           # Tiene que matchear con el label del Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
